### ISSUE TITLE
#1.3.1 Client Meeting @ 5/9/2023 : 10:00

### ISSUE THREAD

**Issue by yichingt** [Inf2001P8-6/INF2001P8-6-Project#1]

**Comment by yichingt** [comment]
task Id 1.3.1
completed on 5 Sep.
allocated time: 5 Sep, 1000 - 1015
description: meeting with client on zoom for requirements gathering and confirmation questions on project. Meeting was started late due to previous groupings overstaying and still asking question in our own timeslot, causing our team's own slot to be overrun to next slot. As rectification to the problem, team had to rush through our meeting agenda to give way to the next time slot after us (1030 slot).
success/completion: completed meeting with qns asked.

**Comment by fatalxs** [comment]
Task ID 1.3.1
Description: Meeting with client on zoom for requirements gathering and confirmation questions on the project/product.
Goals of task: For requirements gathering and confirmation regarding the design of the system/product.
Success or completion criteria: Questions to be asked
Allocated Time: 1 day
Start Date: 5 Sept
End Date: 5 Sept
Owner of task: Syafeen ( @fatalxs )
Priority: High

**Comment by fatalxs** [comment]
Completed on 5 Sept
The tasks has been completed with the questions to client asked and noted down in minutes.
If task was unable to be completed in time, the entire project would be delayed since there would not be any requirements gathered.
Comment for completion of this task was done on 19 Sept as this issue was inadvertently overlooked previously.
