### ISSUE TITLE
#1.4.1 Use Case Diagram UML

### ISSUE THREAD

**Issue by yichingt** [Inf2001P8-6/INF2001P8-6-Project#6]
Task ID 1.4.1
Description: Use Case diagram for the requirements, mainly to do the use case description
Success/Completion: Complete the use case diagram for the project
Allocated Time: 3 Days
Start date and End Date: 5 Sep - 7 Sep
Owner: Gabriel
Priority: Medium

**Comment by Renziah** [comment]
Work Done: Completed
Has the work been committed to repo?: Yes
How does work affect completion?: No other tasks were push back
Any changes to success or completion criteria: No.
Start date and end date: 5- 7 Sep

**Comment by Renziah** [comment]
Task ID 1.4.1
Description: Use Case diagram for the requirements needs to be reviewed after new information
Success/Completion: Complete the use case diagram for the project with the new information in mind
Allocated Time: 3 Days
Start date and End Date: 11 - 13 Sep
Owner: Gabriel
Priority: Medium

**Comment by Renziah** [comment]
Work Done: Reopened
Has the work been committed to repo?: Yes
How does work affect completion?: This task was reopened due to newly received information, pushed back some tasks minorly.
Any changes to success or completion criteria: Yes. Accuracy of the Use Case Diagram.
Start date and end date: 11- 13 Sep
